name: Build Images

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo -E images/install-dependencies.sh
      - name: Build Rootfs
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: sudo -E images/build-rootfs.sh
      - name: Pack Image
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: sudo -E images/pack-image.sh

