name: Build LXD Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      SOURCE_URL: http://azure.archive.ubuntu.com/ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo -E images/install-dependencies.sh
      - name: Build Rootfs
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: sudo -E images/build-rootfs.sh
      - name: Pack Image
        env:
          RUNNER_TEMP: ${{ runner.temp }}
        run: sudo -E images/pack-image.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-vm
          path: ${{ runner.temp }}/build/*
